# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 487686982d67a7444a2801770690c1e2aa4d2ec628b8ef3438a31ef7cc0f77791f17488b817f4107ca1a8ab7319f4fa532ab2f2efc2878d463ef264aab8b0302

test:
  secret_key_base: e93b991b4a2abf144d2dc15ba47f4a937b3f563f07684aeadd11c477a357177d8346a93988ebd5310eaa5e40e24459dadc50bb66e902433969a6da2ad250f220

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
